dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - yarn install

# We are running browser tests
before_script:
  - export TZ=Europe/Helsinki
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn lint
  - yarn test:ci

after_success:
  - codecov < coverage/lcov.info
